# Generated by Django 2.2.1 on 2019-08-02 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.IntegerField(default=None)),
                ('conf_factory', models.CharField(max_length=200)),
                ('conf1', models.CharField(max_length=200)),
                ('conf2', models.CharField(max_length=200)),
                ('conf3', models.CharField(max_length=200)),
                ('conf4', models.CharField(max_length=200)),
                ('conf5', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=200)),
                ('last_msg', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('name_contact', models.CharField(max_length=200)),
                ('tel_contact', models.CharField(max_length=200)),
                ('email_contact', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualmachine.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.IntegerField(default=None)),
                ('conf_factory', models.CharField(max_length=200)),
                ('conf_rx', models.CharField(max_length=200)),
                ('conf_tx', models.CharField(max_length=200)),
                ('sample_rate', models.IntegerField(default=None)),
                ('version', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=200)),
                ('last_msg', models.FloatField(default=None)),
                ('gw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualmachine.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(default=None)),
                ('channel', models.IntegerField(default=None)),
                ('label', models.CharField(max_length=200)),
                ('enable', models.BooleanField(default=True)),
                ('interruption', models.BooleanField(default=True)),
                ('type_trigger', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('datatype', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)])),
                ('subsample_rate', models.IntegerField(blank=True, default=None, null=True)),
                ('high_threshold', models.FloatField(blank=True, default=None, null=True)),
                ('low_threshold', models.FloatField(blank=True, default=None, null=True)),
                ('delta', models.FloatField(blank=True, default=None, null=True)),
                ('request_status', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('version', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('key', models.IntegerField(default=None)),
                ('gw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualmachine.Gateway')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualmachine.Terminal')),
            ],
        ),
        migrations.AddField(
            model_name='gateway',
            name='vm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualmachine.VirtualMachine'),
        ),
    ]
